### ISSUE TITLE
Error: Meld_graph script: run_script_segmentation.py

### ISSUE THREAD

**Issue by farah-naz01** [MELDProject/meld_graph#34]
Hi,
I am trying meld_graph in a docker container. Since I had already run the Fastsurfer, so I copied the Fastsurfer output in the meld-graph output folder. After running the command:

"docker-compose run meld_graph python scripts/new_patient_pipeline/new_pt_pipeline.py -harmo_code H120 -ids list_subjects.txt -demos /data/demographics_file_H120.csv --parallelise --fastsurfer --harmo_only"

I encountered this error. 
 
**Terminal Output:**

STEP 1 - test017: Fastsurfer outputs already exists for subject test017. Freesurfer will be skipped
STEP 1 - test018: Fastsurfer outputs already exists for subject test018. Freesurfer will be skipped
STEP 1 - test012: Fastsurfer outputs already exists for subject test012. Freesurfer will be skipped
STEP 1 - test009: Fastsurfer outputs already exists for subject test009. Freesurfer will be skipped
STEP 1 - test019: Fastsurfer outputs already exists for subject test019. Freesurfer will be skipped
STEP 1 - test020: Fastsurfer outputs already exists for subject test020. Freesurfer will be skipped
Traceback (most recent call last):
  File "/app/scripts/new_patient_pipeline/new_pt_pipeline.py", line 144, in <module>
    result = run_script_segmentation(
  File "/app/scripts/new_patient_pipeline/run_script_segmentation.py", line 393, in run_script_segmentation
    subject_ids_succeed = run_subjects_segmentation_parallel(subject_ids, harmo_code = harmo_code, use_fastsurfer = use_fastsurfer, verbose=verbose)
  File "/app/scripts/new_patient_pipeline/run_script_segmentation.py", line 268, in run_subjects_segmentation_parallel
    subjects_dict = subjects_dict[mask]
TypeError: list indices must be integers or slices, not list
ERROR: 1

(I saw the script: run_script_segmentation.py and the line "subjects_dict = subjects_dict[mask]" causing the error. I am not sure how to resolve it.)

Any help or guidance is appreciated.
Thanks!

**Comment by arovai** [comment]
Hello,
I am not a MELD-graph developer but from what I understand you should probably not specify `--fastsurfer` in your call.
You have already run freesurfer so I don't see the point of asking MELD to run fastsurfer. I wouldn't be surprised if this is the reason for your error.
Hope this helps - again, I am not related to MELD-graph (apart from a being a potential user!), so consider my input with appropriate caution!
Regards
AR

**Comment by kwagstyl** [comment]
Hi both,

Thanks for flagging this.
I've made a ["new_issues"] branch which should deal with this issue. subjects_dict is currently a list so won't accept another list for indexing.
It won't get merged into the main branch until some time next week, but if you'd like to test it fixes your problem, that would be super helpful.
inside meld_graph directory:
git pull
git checkout new_issues

and try rerunning.

Please let me know if that's solved it.
K
