### ISSUE TITLE
meld_params/Norm_controls_parameters_combat.hdf5 is missing from meld_params.zip

### ISSUE THREAD

**Issue by vbeliveau** [MELDProject/meld_graph#35]
The file ```meld_params/Norm_controls_parameters_combat.hdf5``` is missing from the ```meld_params.zip``` archive and leads to the following error when running prediction with hamonization:
```
Use normalisation parameter from /data/meld_params/Norm_controls_parameters_combat.hdf5
Traceback (most recent call last):
  File "/proc_data1/bd5/FCD-tools-evaluation/classifiers/meld_graph/meld_graph-repo/scripts/new_patient_pipeline/new_pt_pipeline.py", line 161, in <module>
    run_script_preprocessing(
  File "/app/scripts/new_patient_pipeline/run_script_preprocessing.py", line 250, in run_script_preprocessing
    run_data_processing_new_subjects(subject_ids,
  File "/app/scripts/new_patient_pipeline/run_script_preprocessing.py", line 199, in run_data_processing_new_subjects
    norm.intra_inter_subject(feature, params_norm = param_norms_file)
  File "/app/meld_graph/data_preprocessing.py", line 1201, in intra_inter_subject
    params = self.read_norm_combat_parameters(feature, params_norm)
  File "/app/meld_graph/data_preprocessing.py", line 597, in read_norm_combat_parameters
    hdf5_file_context = h5py.File(hdf5_file, "r")
  File "/opt/conda/envs/meld_graph/lib/python3.9/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/opt/conda/envs/meld_graph/lib/python3.9/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/data/meld_params/Norm_controls_parameters_combat.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by mathrip** [comment]
Fix with PR #40
